ARG version=40

FROM quay.io/fedora/fedora-minimal:$version as builder
ARG arch=x64
ARG baseurl=https://dl.fedoraproject.org/pub/fedora/linux
WORKDIR /work

# Artifacts from kickstart repository.
RUN . /etc/os-release && curl --location --remote-name-all --remote-time \
	${baseurl}/releases/${VERSION}/Everything/$(uname -m)/os/images/pxeboot/vmlinuz \
	${baseurl}/releases/${VERSION}/Everything/$(uname -m)/os/images/pxeboot/initrd.img \
	${baseurl}/releases/${VERSION}/Everything/$(uname -m)/os/images/install.img

# Artifacts from RPM repository.
RUN microdnf -y install shim-${arch} grub2-efi-${arch} syslinux-tftpboot
RUN . /etc/os-release && cp -p /tftpboot/pxelinux.0 . && cp -p /boot/efi/EFI/${ID}/{shim,grub}${arch}.efi .
