ARG version=40

FROM quay.io/fedora/fedora-minimal:$version as builder
ARG name=Fedora
ARG arch=aa64
ARG baseurl=https://dl.fedoraproject.org/pub/fedora/linux
WORKDIR /root

# Artifacts from kickstart repository.
RUN curl -RLO ${baseurl}/releases/${version}/Everything/$(uname -m)/os/images/pxeboot/vmlinuz
RUN curl -RLO ${baseurl}/releases/${version}/Everything/$(uname -m)/os/images/pxeboot/initrd.img
RUN curl -RLO ${baseurl}/releases/${version}/Everything/$(uname -m)/os/images/install.img

# Artifacts from RPM repository.
RUN microdnf -y install shim-${arch} grub2-efi-${arch}
RUN cp -p /boot/efi/EFI/fedora/{shim,grub${arch}}.efi .
