ARG version=40

FROM quay.io/fedora/fedora-minimal:$version as builder
ARG name=Fedora
ARG arch=aa64
ARG baseurl=https://dl.fedoraproject.org/pub/fedora/linux
WORKDIR /root

# Artifacts from kickstart repository.
RUN . /etc/os-release && curl --location --remote-name-all --remote-time \
	${baseurl}/releases/${VERSION}/Everything/$(uname -m)/os/images/pxeboot/vmlinuz \
	${baseurl}/releases/${VERSION}/Everything/$(uname -m)/os/images/pxeboot/initrd.img \
	${baseurl}/releases/${VERSION}/Everything/$(uname -m)/os/images/install.img

# Artifacts from RPM repository.
RUN microdnf -y install shim-${arch} grub2-efi-${arch}
RUN . /etc/os-release && cp -p /boot/efi/EFI/${ID}/{shim,grub}${arch}.efi .
