ARG version=stream9

FROM quay.io/centos/centos:$version-minimal as builder
ARG arch=x64
ARG baseurl=https://mirror.stream.centos.org
WORKDIR /root

# Artifacts from kickstart repository.
RUN . /etc/os-release && curl --location --remote-name-all --remote-time \
	${baseurl}/${VERSION}-stream/BaseOS/$(uname -m)/os/images/pxeboot/vmlinuz \
	${baseurl}/${VERSION}-stream/BaseOS/$(uname -m)/os/images/pxeboot/initrd.img \
	${baseurl}/${VERSION}-stream/BaseOS/$(uname -m)/os/images/install.img

# Artifacts from RPM repository.
RUN microdnf -y install shim-${arch} grub2-efi-${arch} syslinux-tftpboot
RUN . /etc/os-release && cp -p /tftpboot/pxelinux.0 . && cp -p /boot/efi/EFI/${ID}/{shim,grub}${arch}.efi .
